# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.4'

gem 'active_model_serializers'
gem 'bcrypt', '~> 3.1.7'
gem 'concurrent-ruby', '1.3.4'
gem 'jwt'
gem 'pg', '~> 1.1'
gem 'puma', '~> 6.0'
gem 'pundit', '~> 2.4.0'
gem 'rails', '~> 7.0'
# gem 'redis', '~> 4.0'

gem 'bootsnap', '>= 1.4.4', require: false
gem 'rack-cors'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-factory_bot', require: false
end

group :test do
  gem 'shoulda-matchers', '~> 6.0'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'bullet', github: 'flyerhzm/bullet'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
